name: MCScoreboard
version: 1.0.0
main: net.maron_gt123.mcscoreboard.MCScoreboardPlugin
api-version: '1.21'
author: maron_gt123
description: Display server information on the sidebar scoreboard.
commands:
  msb:
    description: msb command
    usage: /msb